version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: multi_platform_support
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      frontend-patch-minor:
        update-types: [minor, patch]
  - package-ecosystem: cargo
    directory: /src-tauri
    target-branch: multi_platform_support
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      rust-patch-minor:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    target-branch: multi_platform_support
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
